version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: assets-inventory-dev
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: bash
